import Head from 'next/head'
import React from 'react'
import Homee from './home'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Turkish restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tr.jpeg" />
      </Head>

      <main>
        <Homee></Homee>
       
      </main>
    </div>
  )
}
